language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - rbx-2.1.1
  - ruby-head
  - 1.8.7
  - 2.0.0
  - 2.1.0
  - jruby-18mode
  - jruby-19mode
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: 1.8.7
    - rvm: rbx-2.1.1
